apiVersion: v1
kind: Service
metadata:
  name: object-detection-cloud-origin
  namespace: light-object-detect
spec:
  selector:
    app.kubernetes.io/name: light-object-detect
  ports:
  - name: http
    port: 8000
    targetPort: 8000
